2014/05/12 21:46:50 [error] [exception.CDbException] could not find driver
2014/05/12 21:46:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection.' in D:\YiiRoot\db\CDbConnection.php:388
Stack trace:
#0 D:\YiiRoot\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\YiiRoot\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\YiiRoot\base\CModule.php(387): CDbConnection->init()
#3 D:\YiiRoot\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\YiiRoot\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\YiiRoot\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 D:\YiiRoot\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 D:\YiiRoot\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 D:\YiiRoot\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 D:\YiiRoot\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 D:\YiiRoot\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 D:\YiiRoot\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 D:\YiiRoot\zii\widgets\CListView.php(211): CBaseListView->init()
#13 D:\YiiRoot\web\CBaseController.php(147): CListView->init()
#14 D:\YiiRoot\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 D:\webroot\test.loc\protected\views\post\index.php(9): CBaseController->widget('zii.widgets.CLi...', Array)
#16 D:\YiiRoot\web\CBaseController.php(126): require('D:\\webroot\\test...')
#17 D:\YiiRoot\web\CBaseController.php(95): CBaseController->renderInternal('D:\\webroot\\test...', Array, true)
#18 D:\YiiRoot\web\CController.php(869): CBaseController->renderFile('D:\\webroot\\test...', Array, true)
#19 D:\YiiRoot\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 D:\webroot\test.loc\protected\controllers\PostController.php(136): CController->render('index', Array)
#21 D:\YiiRoot\web\actions\CInlineAction.php(49): PostController->actionIndex()
#22 D:\YiiRoot\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#25 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#29 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 D:\YiiRoot\web\CWebApplication.php(282): CController->run('')
#31 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('')
#32 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#33 D:\webroot\test.loc\index.php(11): CApplication->run()
#34 {main}
REQUEST_URI=/
---
2014/05/12 21:56:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in D:\YiiRoot\web\CWebApplication.php:286
Stack trace:
#0 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\webroot\test.loc\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2014/05/12 21:56:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "r/gii".' in D:\YiiRoot\web\CWebApplication.php:286
Stack trace:
#0 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('r/gii')
#1 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\webroot\test.loc\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/r/gii
---
2014/05/12 21:57:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in D:\YiiRoot\web\CWebApplication.php:286
Stack trace:
#0 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\webroot\test.loc\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/gii
---
2014/05/12 22:45:07 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.category' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `category`.
2014/05/12 22:53:53 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.category' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `category`.
2014/05/12 22:53:57 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'blog.category' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `category`.
2014/05/12 23:05:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "add".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('add')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('add')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/add')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/add
---
2014/05/12 23:06:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "add".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('add')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('add')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/add/vi...')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/add/view/1
---
2014/05/12 23:06:31 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view/1')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view/1
---
2014/05/12 23:06:33 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view/1')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view/1
---
2014/05/12 23:06:39 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view
---
2014/05/12 23:11:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "vew".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('vew')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('vew')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/vew/1')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/vew/1
---
2014/05/12 23:12:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "2".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('2')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('2')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/2/vew')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/2/vew
---
2014/05/12 23:12:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "1".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('1')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('1')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/1/vew')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/1/vew
---
2014/05/12 23:12:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "1".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('1')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('1')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/1/vew')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/1/vew
---
2014/05/12 23:15:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "1".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('1')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('1')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/1/vew')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/1/vew
---
2014/05/12 23:15:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "2".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('2')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('2')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/2/vew')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/2/vew
---
2014/05/12 23:15:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "vew".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('vew')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('vew')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/vew/1')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/vew/1
---
2014/05/12 23:15:22 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view/1')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view/1
---
2014/05/12 23:15:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "1".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('1')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('1')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/1/view')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/1/view
---
2014/05/12 23:15:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "2".' in D:\YiiRoot\web\CController.php:483
Stack trace:
#0 D:\YiiRoot\web\CController.php(270): CController->missingAction('2')
#1 D:\YiiRoot\web\CWebApplication.php(282): CController->run('2')
#2 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/2/view')
#3 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\webroot\test.loc\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/category/2/view
---
2014/05/12 23:15:38 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view/2')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view/2
---
2014/05/12 23:15:41 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view/2')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view/2
---
2014/05/12 23:17:26 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view/2')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view/2
---
2014/05/12 23:17:29 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view/1')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view/1
---
2014/05/12 23:17:35 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\YiiRoot\web\CController.php:336
Stack trace:
#0 D:\YiiRoot\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\YiiRoot\web\CWebApplication.php(282): CController->run('view')
#9 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/view')
#10 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\webroot\test.loc\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/category/view
---
2014/05/12 23:18:16 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1. The SQL statement executed was: INSERT INTO `tbl_category` (`name`) VALUES (:yp0).
2014/05/12 23:18:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1' in D:\YiiRoot\db\CDbCommand.php:358
Stack trace:
#0 D:\YiiRoot\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 D:\YiiRoot\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 D:\webroot\test.loc\protected\controllers\CategoryController.php(73): CActiveRecord->save()
#3 D:\YiiRoot\web\actions\CInlineAction.php(49): CategoryController->actionCreate()
#4 D:\YiiRoot\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#11 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\YiiRoot\web\CWebApplication.php(282): CController->run('create')
#13 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/create')
#14 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\webroot\test.loc\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/category/create
HTTP_REFERER=http://test.loc/category/create
---
2014/05/12 23:21:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1. The SQL statement executed was: INSERT INTO `tbl_category` (`name`) VALUES (:yp0).
2014/05/12 23:21:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1' in D:\YiiRoot\db\CDbCommand.php:358
Stack trace:
#0 D:\YiiRoot\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 D:\YiiRoot\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 D:\webroot\test.loc\protected\controllers\CategoryController.php(73): CActiveRecord->save()
#3 D:\YiiRoot\web\actions\CInlineAction.php(49): CategoryController->actionCreate()
#4 D:\YiiRoot\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#11 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\YiiRoot\web\CWebApplication.php(282): CController->run('create')
#13 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/create')
#14 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\webroot\test.loc\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/category/create
HTTP_REFERER=http://test.loc/category/create
---
2014/05/12 23:22:49 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1. The SQL statement executed was: INSERT INTO `tbl_category` (`name`) VALUES (:yp0).
2014/05/12 23:22:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1' in D:\YiiRoot\db\CDbCommand.php:358
Stack trace:
#0 D:\YiiRoot\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 D:\YiiRoot\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 D:\webroot\test.loc\protected\controllers\CategoryController.php(73): CActiveRecord->save()
#3 D:\YiiRoot\web\actions\CInlineAction.php(49): CategoryController->actionCreate()
#4 D:\YiiRoot\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#11 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\YiiRoot\web\CWebApplication.php(282): CController->run('create')
#13 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/create')
#14 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\webroot\test.loc\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/category/create
HTTP_REFERER=http://test.loc/category/create
---
2014/05/12 23:25:35 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1. The SQL statement executed was: INSERT INTO `tbl_category` (`name`) VALUES (:yp0).
2014/05/12 23:25:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1' in D:\YiiRoot\db\CDbCommand.php:358
Stack trace:
#0 D:\YiiRoot\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 D:\YiiRoot\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 D:\webroot\test.loc\protected\controllers\CategoryController.php(73): CActiveRecord->save()
#3 D:\YiiRoot\web\actions\CInlineAction.php(49): CategoryController->actionCreate()
#4 D:\YiiRoot\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#11 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\YiiRoot\web\CWebApplication.php(282): CController->run('create')
#13 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/create')
#14 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\webroot\test.loc\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/category/create
HTTP_REFERER=http://test.loc/category/create
---
2014/05/12 23:27:04 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1. The SQL statement executed was: INSERT INTO `tbl_category` (`name`) VALUES (:yp0).
2014/05/12 23:27:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1' in D:\YiiRoot\db\CDbCommand.php:358
Stack trace:
#0 D:\YiiRoot\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 D:\YiiRoot\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 D:\webroot\test.loc\protected\controllers\CategoryController.php(73): CActiveRecord->save()
#3 D:\YiiRoot\web\actions\CInlineAction.php(49): CategoryController->actionCreate()
#4 D:\YiiRoot\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#11 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\YiiRoot\web\CWebApplication.php(282): CController->run('create')
#13 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/create')
#14 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\webroot\test.loc\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/category/create
HTTP_REFERER=http://test.loc/category/create
---
2014/05/12 23:27:07 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1. The SQL statement executed was: INSERT INTO `tbl_category` (`name`) VALUES (:yp0).
2014/05/12 23:27:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xD0\x9F\xD0\xB5\xD1\x80...' for column 'name' at row 1' in D:\YiiRoot\db\CDbCommand.php:358
Stack trace:
#0 D:\YiiRoot\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 D:\YiiRoot\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 D:\webroot\test.loc\protected\controllers\CategoryController.php(73): CActiveRecord->save()
#3 D:\YiiRoot\web\actions\CInlineAction.php(49): CategoryController->actionCreate()
#4 D:\YiiRoot\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\YiiRoot\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\YiiRoot\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\YiiRoot\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\YiiRoot\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\YiiRoot\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\YiiRoot\web\CController.php(291): CFilterChain->run()
#11 D:\YiiRoot\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\YiiRoot\web\CWebApplication.php(282): CController->run('create')
#13 D:\YiiRoot\web\CWebApplication.php(141): CWebApplication->runController('category/create')
#14 D:\YiiRoot\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\webroot\test.loc\index.php(11): CApplication->run()
#16 {main}
REQUEST_URI=/category/create
HTTP_REFERER=http://test.loc/category/create
---
